#Create a Book
###
POST http://localhost:3000/books
Content-Type: application/json

{
  "name": "Carte de pisici",
  "author": "Florin Dragoi",
  "description": "",
  "categoryId": 11
}
###

###
POST http://localhost:3000/books
Content-Type: application/json

{
  "name": "Create a book 5",
  "author": "Florin Dragoi",
  "description": "Not today",
  "categoryId": 5
}
###


#List all Books
###
GET http://localhost:3000/books
###


#List a Book by Id
###
GET http://localhost:3000/books/11
###


#List Books by Category
###
GET http://localhost:3000/books/category/3?skip=0&limit=10
###


#Update a Book
###
PATCH http://localhost:3000/books/11
Content-Type: application/json

{
  "name": "My books is yours",
  "author": "Iuli",
  "description": "Tomorrow is today",
  "categoryId": 10
}
###


#Delete a Book
###
DELETE http://localhost:3000/books/9
###
