#Create a Category
###
POST http://localhost:3000/categories
Content-Type: application/json

{
  "name": "Animale"
}
###


#Create a Subcategory
###
POST http://localhost:3000/categories
Content-Type: application/json

{
  "name": "Pisici",
  "parentCategoryId": 7
}
###


#List all Categories
###
GET http://localhost:3000/categories
###


#List a Category by Id
###
GET http://localhost:3000/categories/10
###


#Update a Category
###
PATCH http://localhost:3000/categories/11
Content-Type: application/json

{
  "parentCategoryId": 12
}
###


#Delete a Category and its books
###
DELETE http://localhost:3000/categories/12
###
